#!/bin/bash

set -e

smoked=/var/lib/drag/smoked

if [[ -z "$@" ]]; then
	echo "You can't stub that!"
	echo
	exit 1
else
	if command -v sudo >/dev/null 2>&1; then
                SUDO=sudo
       	elif command -v doas >/dev/null 2>&1; then
               	SUDO=doas
        elif command -v su >/dev/null 2>&1; then
               	SUDO="su root"
       	fi
	if [ $EUID == 0 ]; then
		SUDO=
	fi
        [[ $EUID != 0 && $SUDO = "" ]] && echo "Please install su, sudo, or doas to escalate privileges." && exit 1
	cigs=""
	for cig in $@; do
		if [[ ! -d $smoked/$cig ]]; then
			echo "$cig has not been smoked!"
			echo
		else
			export smoked cig
	                $SUDO bash -c "
			if [[ -f '$smoked/$cig'/clutter ]]; then
				while IFS= read -r file; do
					rm -fv \"\$file\"
					while [[ ! -z \"\$file\" ]]; do
						file=\"\${file%\/*}\"
						rmdir \"\$file\" 2>/dev/null
					done
				done < '$smoked/$cig'/clutter
			fi
			rm -rf '$smoked/$cig'

			cd /
			if [ -d '$ashtray/../stash/$cig' ]; then 
			for i in \$(find '$ashtray/../stash/$cig/' -name *.install); do
			        (source \"\$i\"
			        if declare -f post_remove > /dev/null; then post_remove; fi)
			done
			fi
			"
		fi
		echo "Stubbed $cig"
		echo
		cigs="$cigs $cig,"
	done
	cigs="${cigs%%,}"
	echo "Stubbed$cigs"
	echo
	exit 0
fi
