#!/bin/bash

set -e

ashtray=$HOME/.cache/drag/ashtray

if [[ -z "$@" ]]; then
        echo "You can't blaze that!"
        echo
        exit 1
else
        if command -v sudo >/dev/null 2>&1; then
                SUDO=sudo
        elif command -v doas >/dev/null 2>&1; then
                SUDO=doas
        elif command -v su >/dev/null 2>&1; then
                SUDO="su root"
        fi 
        if [ $EUID == 0 ]; then
                SUDO=
        fi
        [[ $EUID != 0 && $SUDO = "" ]] && echo "Please install su, sudo, or doas to escalate privileges." && exit 1
        cigs=""
	export ashtray
        for cig in "$@"; do
		echo
		read -p "Blaze $cig's ashtray (build and source)? [y/N] " burn
		case $burn in
			[yY])
			rm -rf $ashtray/$cig >/dev/null 2>&1 || $SUDO bash -c "rm -rf $ashtray/$cig"
			read -p "Blaze $cig's stash (PKGBUILD)? [y/N] " burn
			case $burn in
				[yY])
				rm -rf $ashtray/../stash/$cig;;
				*)
				;;
			esac;;
			*)
			;;
		esac
		cigs="$cigs $cig,"
		echo
	done
	cigs="${cigs%%,}"
        echo "Blazed$cigs"
	echo
	exit 0
fi
