#!/bin/bash

if [ -z "$(ls $DRAG_ROOT/var/cache/drag/stash/)" ]; then
        echo "You're stash is empty!"
        echo "You could add vi to your stash by running:"
        echo "stash vi"
else
	echo "Stash:"
        cigs=$(find $DRAG_ROOT/var/cache/drag/stash/* -maxdepth 0 -exec basename {} \;)
        echo $cigs
fi
echo

if [ -z "$(ls $DRAG_ROOT/var/lib/drag/smoked/)" ]; then
	echo "You haven't smoked yet. Probably for the best."
else
	echo "Smoked:"
	cigs=$(find $DRAG_ROOT/var/lib/drag/smoked/* -maxdepth 0 -exec basename {} \;)
	echo $cigs
fi
echo
