#!/bin/bash

set -e

if command -v sudo >/dev/null 2>&1; then
        SUDO=sudo
elif command -v doas >/dev/null 2>&1; then
        SUDO=doas
elif command -v su >/dev/null 2>&1; then
        SUDO="su root"
fi 
if [ $EUID == 0 ]; then
        SUDO=
fi
[[ $EUID != 0 && $SUDO = "" ]] && echo "Please install su, sudo, or doas to escalate privileges." && exit 1

echo "Hotboxing..."
export home=$HOME
$SUDO bash -c "rm -rf '$home'/.cache/drag"
echo "Stoned!"
