#!/bin/bash

set -e

if [[ "$EUID" -ne 0 ]]; then
	echo "Please run drag commands with root privileges"
	echo
	exit 1
elif [ -z "$(ls $DRAG_ROOT/var/lib/drag/smoked/)" ]; then
        echo "You haven't smoked yet. Probably for the best."
	echo
	exit 1
else
	if [[ -n $@ ]]; then
		echo "ARGUMENTS NOT CONSIDERED"
		echo "BE WARNED!"
		echo
	fi
	for cig in $DRAG_ROOT/var/lib/drag/smoked/*; do
		if [ -d $DRAG_ROOT/var/cache/drag/stash/$cig ]; then
			echo "$cig has not been stashed!"
			echo 
			exit 1
		fi
		cig="${cig##*/}"
		chronic=false
		if [ -f $DRAG_ROOT/etc/drag/chronic ]; then
			while read -r ccig; do
				if [ $ccig == $cig ]; then
					chronic=true
				fi
			done < $DRAG_ROOT/etc/drag/chronic
		fi
		(source $DRAG_ROOT/var/cache/drag/stash/$cig/PKGBUILD
		if [[ $(cat $DRAG_ROOT/var/lib/drag/smoked/$cig/ver) != $pkgver && $chronic == false ]]; then
			echo "Smoking $cig"
			smoke $cig
			cigs="$cigs $cig,"
		fi)
	done
	cigs="${cigs%%,}"
	echo
	if [[ -n $cigs ]]; then
		echo "Hotboxed$cigs"
	fi
	echo
	exit 0
fi
