#!/bin/bash

set -e

ashtray=$HOME/.cache/drag/ashtray

if [[ -z "$@" ]]; then
        echo "You can't smoke that!"
        echo
        exit 1
else
        if command -v sudo >/dev/null 2>&1; then
                SUDO=sudo
        elif command -v doas >/dev/null 2>&1; then
                SUDO=doas
        elif command -v su >/dev/null 2>&1; then
                SUDO="su root"
        fi 
 	if [ $EUID == 0 ]; then
	        SUDO=
        fi
        [[ $EUID != 0 && $SUDO = "" ]] && echo "Please install su, sudo, or doas to escalate privileges." && exit 1
        cigs=""
	override=false
	blaze=false
	if [[ "$@" == "-o "* || "$@" == "-bo "* || "$@" == "-ob "* ]]; then
		override=true
	fi
	if [[ "$@" == "-b "* || "$@" == "-bo "* || "$@" == "-ob "* ]]; then
		blaze=true
	fi
        for cig in "$@"; do
		if [[ $blaze == true && $cig != "-o" && $cig != "-b" && $cig != "-ob" && $cig != "-bo" ]]; then
			blaze $cig
		fi
		if [ $cig == ca-certificates ]; then
                        echo "Smoking ca-certificates"
                        mkdir -p $ashtray/$cig/src
                        cd $ashtray/$cig/src
                        curl -Lqo ca-certificates.crt https://curl.se/ca/cacert.pem
                        curl -Lqo certsha256sum       https://curl.se/ca/cacert.pem.sha256
                        actual=$(sha256sum ca-certificates.crt)
                        actual=${actual%%\ *}
                        if [[ "$(cat certsha256sum)" == *$actual* ]]; then
                                echo "Verified ca-certificates"
                                echo
                                $SUDO bash -c "set -e
                                cp ca-certificates.crt /etc/ssl/certs/
                                cp ca-certificates.crt /etc/ssl/cert.pem"
                                cigs="$cigs $cig,"
                        else
                                echo "CHECKSUM VALIDATION FAILED FOR ca-certificates!"
                                echo
                                exit 1
                        fi
		elif [ $cig == drag ]; then
			echo "Smoking drag"
			cd $ashtray
			git clone https://github.com/catnipsta/drag
			chmod +x drag/scripts/*
			$SUDO bash -c "cp drag/scripts/* /usr/bin/"
			rm -rf drag
			cigs="$cigs $cig,"
                elif [[ -d /var/lib/drag/smoked/$cig && $override == false ]]; then
                        echo
                        echo "$cig already smoked"
			echo "Either stub $cig first, or override this with:"
			echo "smoke -o $cig"
                        echo
                	cigs="$cigs $cig,"
                elif [[ $cig != "-o" && $cig != "-b" && $cig != "-ob" && $cig != "-bo" ]]; then
                if [ ! -f $ashtray/$cig/.rolled ]; then
                        echo "$cig not rolled"
                        roll $cig
                fi
                if [[ -z $(ls $ashtray/$cig/pkg) ]]; then
                        rm $ashtray/$cig/.rolled
                        echo
                        echo "No files found in $cig's pkgdir"
                        echo
                        exit 1
                fi

                export ashtray cig

                $SUDO bash -c "set -e
mkdir -p '/var/lib/drag/smoked/$cig'
cp '$ashtray/$cig/ver' '/var/lib/drag/smoked/$cig/ver'
while IFS= read -r file; do
        if [[ \"\$(file \"\$file\")\" != *\": \"*\"directory\"* && \"\$(file \"\$file\")\" != *\": \"*\"symbolic link\"* ]]; then
		mode=\"\$(stat -c %a \"\$file\")\"
                file=\"\${file#*'$cig'/pkg}\"
                echo \"\$file\" >> '/var/lib/drag/smoked/$cig/clutter'
                if [[ \$cig != file ]]; then
			install -vm\"\$mode\" '$ashtray/$cig'/pkg\"\$file\" \"\$file\"
		else
			cp -av '$ashtray/$cig'/pkg\"\$file\" \"\$file\"
		fi
        elif [[ \"\$(file \"\$file\")\" == *\": \"*\"symbolic link\"* ]]; then
                file=\"\${file#*'$cig'/pkg}\"
                echo \"\$file\" >> '/var/lib/drag/smoked/$cig/clutter'
		ln -sfv \"\$(readlink '$ashtray/$cig'/pkg\"\$file\")\" \"\$file\"
	else
		mode=\"\$(stat -c %a \"\$file\")\"
		mkdir -vp \"\${file#*'$cig'/pkg}\"
		chmod -v \"\$mode\" \"\${file#*'$cig'/pkg}\"
        fi
done < <(find '$ashtray/$cig'/pkg/*)

cd /
if [ -d '$ashtray/../stash/$cig' ]; then 
for i in \$(find '$ashtray/../stash/$cig/' -name *.install); do
	(source \"\$i\"
	if declare -f post_install > /dev/null; then post_install; fi)
done
fi
" || $SUDO bash -c "rm -rf '/var/lib/drag/smoked/$cig'"

                echo "Smoked $cig"
                echo
                cigs="$cigs $cig,"
                fi
        done
        cigs="${cigs%%,}"
        echo
        echo "Smoked$cigs"
        echo
        exit 0
fi
