#!/bin/bash

set -e

ashtray=$HOME/.cache/drag/ashtray

if [[ -z "$@" ]]; then
        echo "You can't smoke that!"
        echo
        exit 1
else
        cigs=""
        for cig in "$@"; do
                if [[ ! -d "$ashtray/$cig" ]]; then
                        echo "$cig has not been pinched!"
                        echo
                        exit 1
                elif [[ -z $(ls $ashtray/$cig/pkg) ]]; then
                        echo "$cig's pkgdir is empty!"
                        echo
                        exit 1
                fi
		if command -v sudo >/dev/null 2>&1; then
			SUDO=sudo
		elif command -v doas >/dev/null 2>&1; then
			SUDO=doas
		elif command -v su >/dev/null 2>&1; then
			SUDO=su
		fi
		export DRAG_ROOT ashtray cig
		$SUDO bash -c "
mkdir -p '$DRAG_ROOT/var/lib/drag/smoked/$cig'
cp '$ashtray/$cig/ver' '$DRAG_ROOT/var/lib/drag/smoked/$cig/ver'
for file in \$(find '$ashtray/$cig'/pkg/* \( -type f -o -type l -o -type s -o -type p \)); do
	echo \"\${file#*/pkg}\" >> '$DRAG_ROOT/var/lib/drag/smoked/$cig/clutter'
done
rsync -a --keep-dirlinks '$ashtray/$cig/pkg/' '$DRAG_ROOT/'
"
                echo
                echo "Smoked $cig"
                echo
                cigs="$cigs $cig,"
        done
        cigs="${cigs%%,}"
        echo
        echo "Smoked$cigs"
        echo
        exit 0
fi
