#!/bin/bash

stash=$HOME/.cache/drag/stash

mkdir -p $stash

if [[ -z "$@" ]]; then
        echo "Stashing previous..."
	echo
	for cig in $stash/* $DRAG_ROOT/var/lib/drag/smoked/*; do
		cig="${cig##*/}"
		if [[ ! "$cigs" =~ "$cig" ]]; then
			 cigs+="$cig "
		fi
	done
	stash $cigs
	exit 0
else
	cigs=""
	for cig in "$@"; do
		echo "Taking a drag..."
		tmp1=$(mktemp)
		tmp2=$(mktemp)
		wget -q -O $tmp1 https://gitlab.archlinux.org/archlinux/packaging/packages/$cig/-/archive/main/$cig-main.tar.gz
		wget -q -O $tmp2 https://aur.archlinux.org/cgit/aur.git/snapshot/$cig.tar.gz
		if file $tmp1 | grep -q "gzip"; then
			echo "Stashing $cig from Arch's repo..."
			cigs="$cigs $cig,"
			if [ -d $stash/$cig ]; then
				rm -rf $stash/$cig
			fi
			tar -xzf $tmp1 -C $stash/
			mv $stash/$cig-main $stash/$cig
			sed -i 's/arch-meson/meson/g' $stash/$cig/PKGBUILD
		elif $(file $tmp2 | grep -q "gzip"); then
			echo "Stashing $cig from the AUR..."
			cigs="$cigs $cig,"
			if [ -d $stash/$cig ]; then
				rm -rf $stash/$cig
			fi
			tar -xzf $tmp2 -C $stash/
			sed -i 's/arch-meson/meson/g' $stash/$cig/PKGBUILD
		else
			echo
			echo "Could not find $cig in Arch's main repo or the AUR!"
			cigs="${cigs%%,}"
			if [[ -n "$cigs" ]]; then
				echo "Stashed$cigs"
			fi
			echo
			exit 1
		fi
		rm $tmp1 $tmp2
	done
	cigs="${cigs%%,}"
	if command -v vi >/dev/null 2>&1; then
		EDITOR=vi
	elif command -v vim >/dev/null 2>&1; then
		EDITOR=vim
	elif command -v nvim >/dev/null 2>&1; then
		EDITOR=nvim
	elif command -v emacs >/dev/null 2>&1; then
		EDITOR=emacs
	elif command -v nano >/dev/null 2>&1; then
		EDITOR=nano
	fi
	for cig in "$@"; do
		$EDITOR $stash/$cig/PKGBUILD
	done
	echo
	echo "Stashed$cigs"
	echo
	exit 0
fi
