#!/bin/bash

stash=$HOME/.cache/drag/stash

mkdir -p $stash

if [[ -z "$@" ]]; then
        echo "You can't stash that!"
	echo
	exit 1
else
	cigs=""
	for cig in "$@"; do
		echo "Taking a drag..."
		tmp1=$(mktemp)
		tmp2=$(mktemp)
		wget -O $tmp1 https://gitlab.archlinux.org/archlinux/packaging/packages/$cig/-/archive/main/$cig-main.tar.gz
		wget -O $tmp2 https://aur.archlinux.org/cgit/aur.git/snapshot/$cig.tar.gz
		if file $tmp1 | grep -q "gzip"; then
			echo "Stashing $cig from Arch's repo..."
			cigs="$cigs $cig,"
			if [ -d $stash/$cig ]; then
				rm -rf $stash/$cig
			fi
			tar -xzf $tmp1 -C $stash/
			mv $stash/$cig-main $stash/$cig
		elif file $tmp2 | grep -q "gzip"; then
			echo "Stashing $cig from the AUR..."
			cigs="$cigs $cig,"
			if [ -d $stash/$cig ]; then
				rm -rf $stash/$cig
			fi
			tar -xzf $tmp2 -C $stash/
		else
			echo
			echo "Could not find $cig in Arch's main repo or the AUR!"
			cigs="${cigs%%,}"
			if [[ -n "$cigs" ]]; then
				echo "Stashed$cigs"
			fi
			echo
			exit 1
		fi
		rm $tmp1 $tmp2
	done
	cigs="${cigs%%,}"
	snoop $@
	echo
	echo "Stashed$cigs"
	echo
	exit 0
fi
