#!/bin/bash

set -e

smoked=/var/lib/drag/smoked

if [[ -z "$@" ]]; then
	echo "You can't stub that!"
	echo
	exit 1
else
	cigs=""
	for cig in $@; do
		if [[ ! -d $smoked/$cig ]]; then
			echo "$cig has not been smoked!"
			echo
		else
			if command -v sudo >/dev/null 2>&1; then
       		                SUDO=sudo
               		elif command -v doas >/dev/null 2>&1; then
                       		SUDO=doas
                	elif command -v su >/dev/null 2>&1; then
                        	SUDO="su root"
                	fi
			if [ $EUID == 0 ]; then
				SUDO=
			fi
	                [[ $EUID != 0 && $SUDO = "" ]] && echo "Please install su, sudo, or doas to escalate privileges." && exit 1
			export smoked cig
	                $SUDO bash -c "
			if [[ -f '$smoked/$cig'/clutter ]]; then
				while IFS= read -r file; do
					rm -fv \"\$file\"
				done < '$smoked/$cig'/clutter
			fi
			rm -rf '$smoked/$cig'

			if [ -d '$ashtray/../stash/$cig' ]; then 
			for i in \$(find '$ashtray/../stash/$cig/' -name *.install); do
			        (source \"\$i\"
			        if declare -f post_remove > /dev/null; then post_remove; fi)
			done
			fi
			"
		fi
		echo "Stubbed $cig"
		cigs="$cigs $cig,"
	done
	echo
	cigs="${cigs%%,}"
	echo "Stubbed$cigs"
	echo
	exit 0
fi
