#!/bin/bash

set -e

smoked=$DRAG_ROOT/var/lib/drag/smoked

if [[ -z "$@" ]]; then
	echo "You can't stub that!"
	echo
	exit 1
else
	cigs=""
	for cig in $@; do
		if [[ ! -d $smoked/$cig ]]; then
			echo "$cig has not been smoked!"
			echo
		else
			if command -v sudo >/dev/null 2>&1; then
       		                SUDO=sudo
               		elif command -v doas >/dev/null 2>&1; then
                       		SUDO=doas
                	elif command -v su >/dev/null 2>&1; then
                        	SUDO="su root"
                	fi
			if [ $EUID == 0 ]; then
				SUDO=
			fi
			export DRAG_ROOT smoked cig
	                $SUDO bash -c "
			export DRAG_ROOT='$DRAG_ROOT'
			export smoked='$smoked'
			export cig='$cig'
			if [[ -f $smoked/$cig/clutter ]]; then
				while IFS= read -r file; do
					rm -f \$DRAG_ROOT\$file
				done < $smoked/$cig/clutter
			fi
			rm -rf $smoked/$cig
			"
		fi
		echo "Stubbed $cig"
		cigs="$cigs $cig,"
	done
	echo
	cigs="${cigs%%,}"
	echo "Stubbed$cigs"
	echo
	exit 0
fi
